# three.js-r99/build/three.js
# three.js-r99/build/three.min.js
# three.js-r99/build/three.module.js


#three.js: three.js.tar.gz
#	tar tvzf $< --strip-components=3

three.js.tar.gz:
	wget -nv -O $@ https://github.com/mrdoob/three.js/archive/r99.tar.gz

